# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build: .
        ports:
          - '8000:80'
        volumes:
            - ./:/var/www/html/plutool
        working_dir: /var/www/html/plutool
        networks:
            - plutool-network
        extra_hosts:
          - "plutool:127.0.0.1"
        depends_on:
            - mysql
        links:
          - mysql
        command: >
          bash -c "composer install &&
          composer update &&
          composer dumpautoload &&
          php artisan migrate &&
          php artisan db:seed &&
          service apache2 restart &&
          npm install &&
          npm run watch"
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'plutool'
            MYSQL_USER: 'plutool'
            MYSQL_PASSWORD: 'plutool'
        volumes:
            - 'mysql:/docker-entrypoint-initdb.d'
        networks:
            - plutool-network
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'
        networks:
            - plutool-network
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - plutool-network
networks:
  plutool-network:
      driver: bridge
volumes:
  mysql:
    driver: local
  redis:
    driver: local
